media:
  input: routes/media
  output: /media
content:
  - name: posts
    label: Posts
    path: data/posts
    type: collection
    view:
      fields: [ title, date ]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
      - name: body
        label: Body
        type: rich-text
